USE [Northwind ]
GO

/****** Object:  Table [dbo].[ExecutionLog]    Script Date: 12/6/2023 6:18:42 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ExecutionLog](
	[LogID] [int] IDENTITY(1,1) NOT NULL,
	[ProcedureName] [nvarchar](255) NULL,
	[ExecutionTime] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[LogID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


